# tuna server configuration

# 进程/服务启动
[server]
daemon = false
worker_processes = 1

# 日志
[log]
file = tuna.log
level = debug

# 线程池
[thread]
worker_threads = 4

# 网络监听/连接池
[net]
listen_port_count = 1
listen_port = 8080
worker_connections = 1024
recycle_connection_wait_sec = 60

# 心跳
[heartbeat]
enable = true
max_wait_sec = 20
timeout_kick = false

# flood检测
[security]
flood_enable = true
flood_interval_ms = 100
flood_kick_count = 10

# 数据库
[mysql]
enable = false
host = 127.0.0.1
port = 3306
user = root
password = 
database = tuna
